---
# =============================================================================
#  Author : Martin AUBEUT
#  Ansible Playbook â€” Installation et configuration ClamAV (antimalware)
#  Usage : ansible-playbook -i inventory.ini anti-malware.yml
#  Version : 1.0 (2025-19-02)
#  Modification :
#  - 2025-19-02 - Initial version
# =============================================================================

- name: Install and configure ClamAV
  hosts: all
  become: true

  tasks:
    - name: Install ClamAV
      apt:
        name:
          - clamav
          - clamav-daemon
        state: present
        update_cache: true

    - name: Stop freshclam for manual update
      systemd:
        name: clamav-freshclam
        state: stopped

    - name: Update virus definitions
      command: freshclam
      changed_when: true

    - name: Enable and start ClamAV services
      systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - clamav-freshclam
        - clamav-daemon